name: Publish image to Docker Hub
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
      - uses: actions/checkout@v3
      - name: build
      - run: |
          docker build -t hossam999/total_seg .
      - name: publish
      - run: |
          docker login -u hossam999 -p ${{ secrets.DOCKER_HUB_TOKEN}}
          docker push hossam999/total_seg:latest
          
