name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag total_seg:latest
    - name: login
      run: docker login -u hossam999 -p ${{secrets.DOCKER_HUB_TOKEN}}
    - name: Tag the Docker image
      run: docker tag total_seg:latest hossam999/total_seg:latest 
    - name: push the Docker image
      run: docker push hossam999/total_seg:latest 
